routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\FrontEndController;
use App\Http\Controllers\OrdersController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () { return view('welcome'); });
Route::get('/', [FrontEndController::class, 'frontend']);

Auth::routes();
  
Route::get('/dashboard', [HomeController::class, 'index'])->name('dashboard');

Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('products', ProductController::class);
    Route::resource('orders', OrdersController::class);

    Route::post('/orders/store', [OrdersController::class, 'store']);
    //Route::post('/orders/update', [OrdersController::class, 'update']);
    Route::get('/products/get/{product_id}', [ProductController::class, 'get']);
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    
    protected $fillable = [
        'name', 'detail', 'image', 'price', 'tags', 'owner'
    ];
}

app/Http/Controllers/ProductController.php
<?php 
namespace App\Http\Controllers;  

use App\Models\Product;
use App\Models\User;
use Illuminate\Http\Request;
use Auth;

class ProductController extends Controller
{
    // Seteamos permisos regun el rol, los usuarios tienen acceso a las diferentes funciones.
    function __construct()
    {
         $this->middleware('permission:product-list|product-create|product-edit|product-delete', ['only' => ['index','show', 'get']]);
         $this->middleware('permission:product-create', ['only' => ['create','store']]);
         $this->middleware('permission:product-edit', ['only' => ['edit','update']]);
         $this->middleware('permission:product-delete', ['only' => ['destroy']]);
    }
    
    /*
     * La funcion index() discrimina entre si el usuario es un Administrador/Moderador o un Cliente.
     * Para cada caso muestra los productos correspondientes, todos para admin/mod y solo aquellos de quien el cliente es propietario.
     * Utilizo serialize() / unserialize() (si, como wordpress) para guardar un array PHP con tags que luego me sirven para filtrar.
     */
    public function index()
    {
        if (Auth::user()->hasRole('Admin') || Auth::user()->hasRole('Moderador')) {
            $products = Product::all();
        } else {
            $products = Product::where('owner', Auth::user()->id)->get();
        }
        
        foreach ($products as $product) {
            $product->tags = unserialize($product->tags);
        }
        
        return view('products.index',compact('products'));
    }   
    
    /*
     * La funcion create() muestra el formulario para crear un producto, no hay mayores aclaraciones.
     */
    public function create()
    {
        $users_query = User::all();
        $users = array();
        
        foreach ($users_query as $user) {
            $users[$user->id] = $user->name.' ('.$user->email.')';
        }
        
        $products = Product::all();
        $tags = [];
        
        foreach ($products as $product) {
            $product->tags = unserialize($product->tags);
            
            foreach ($product->tags as $tag) {
                if (!in_array($tag, $tags)) $tags[$tag] = $tag;
            }
            
        }
        
        return view('products.create',compact('tags', 'users'));
    }
    
    /*
     * La funcion store() guarda una entrada en la Base de Datos luego de hacer ciertas validaciones.
     * Se puede apreciar el manejo de imagenes, que son subidas a la carpeta image/ en el directorio publico de Laravel.
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'detail' => 'required',
            'price'=>'required',
            'image' => 'required|image|mimes:jpg,png,jpeg,gif,svg,webp|max:2048',
            'tags' => 'required',
        ]); 

        $input = $request->all();  

        if ($image = $request->file('image')) {
            $destinationPath = 'image/';
            $productImage = date('YmdHis') . "." . $image->getClientOriginalExtension();
            $image->move($destinationPath, $productImage);
            $input['image'] = "$productImage";
        }
        
        $input['tags'] = serialize($input['tags']);
        $input['owner'] = ($request->owner) ? $request->owner : Auth::user()->id;
        $input['status'] = 'revision';

        Product::create($input);        

        return redirect()->route('products.index')->with('alert', 'success')->with('message','Producto creado correctamente');
    }
    
    /*
     * La funcion show() muestra una vista con los datos del producto sin mayores aclaraciones.
     */
    public function show(Product $product)
    {
        $product->tags = unserialize($product->tags);
            
        return view('products.show',compact('product'));
    }
    
    /*
     * La funcion edit() muestra el formulario para editar un producto.
     * Se discrimina entre usuarios admin/mod y clientes, pues estos ultimos solo pueden editar productos donde son propietarios.
     */
    public function edit(Product $product)
    {
        if (Auth::user()->hasRole('Admin') || Auth::user()->hasRole('Moderador') || $product->owner == Auth::user()->id) {
            $users_query = User::all();
            $users = array();
            
            foreach ($users_query as $user) {
                $users[$user->id] = $user->name.' ('.$user->email.')';
            }
            
            $product->tags = unserialize($product->tags);
                
            return view('products.edit',compact('product', 'users'));
        } else {
            return redirect()->back()->with('alert', 'danger')->with('message','No tiene permisos para editar este producto.');
        }
    }  
    
    /*
     * La funcion update() actualiza la entrada en la BD sin mayores aclaraciones pues es similiar a store().
     */
    public function update(Request $request, Product $product)
    {
        if (Auth::user()->hasRole('Admin') || Auth::user()->hasRole('Moderador') || $product->owner == Auth::user()->id) {
            $request->validate([
                'name' => 'required',
                'detail' => 'required',
                'price'=>'required',
                'tags' => 'required',
            ]);
            
            $input = $request->all();  
            
            if ($image = $request->file('image')) {
                $destinationPath = 'image/';
                $productImage = date('YmdHis') . "." . $image->getClientOriginalExtension();
                $image->move($destinationPath, $productImage);
                $input['image'] = "$productImage";
            }else{
                unset($input['image']);
            }          
            
            $input['tags'] = serialize($input['tags']);
            $input['owner'] = ($request->owner) ? $request->owner : Auth::user()->id;
            
            $product->update($input);
            
            return redirect()->route('products.index')->with('alert', 'success')->with('message','Producto actualizado correctamente');
        } else {
            return redirect()->back()->with('alert', 'danger')->with('message','No tiene permisos para actualizar este producto.');
        }
    }
    
    /*
     * La funcion destroy() elimina la entrada en la BD y borra el archivo asociado.
     */
    public function destroy(Product $product)
    {
        if (Auth::user()->hasRole('Admin') || Auth::user()->hasRole('Moderador') || $product->owner == Auth::user()->id) {
            $ImagePath = 'image/'.$product->image;
            
            unset($ImagePath);
            
            $product->delete();
            
            return redirect()->route('products.index')->with('alert', 'success')->with('message','Producto eliminado');
        } else {
            return redirect()->back()->with('alert', 'danger')->with('message','No tiene permisos para eliminar este producto.');
        }
    }
    
    /*
     * La funcion get() con metodo GET es la que llamamos desde el Frontend mediante Ajax, devuelve el resultado codificado en JSON con json_encode()
     */
    public function get($product_id)
    {
        $product = Product::where('id', $product_id)->first();
        $product->tags = unserialize($product->tags);
        
        return json_encode($product->toArray());
    }
}

resources/views/products/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-12">
            <div class="float-left">
                <h2>Agregar nuevo producto</h2>
            </div>
            <div class="float-right">
                <a class="btn btn-primary" href="{{ route('products.index') }}"> Atras</a>
            </div>
        </div>
    </div>
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Ups!</strong> Hubo algunos problemas con tus datos ingresados.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    {!! Form::open(array('route' => 'products.store','method'=>'POST', 'enctype'=>'multipart/form-data')) !!}
         <div class="row">
		    <div class="col-12">
		        <div class="form-group">
		            <strong>Nombre:</strong>		            
                    {!! Form::text('name', null, array('placeholder' => 'Nombre','class' => 'form-control')) !!}
		        </div>
		    </div>
		    <div class="col-12">
		        <div class="form-group">
		            <strong>Detalles:</strong>
                    {!! Form::textarea('detail', null, array('placeholder' => 'Detalles','class' => 'form-control')) !!}		            
		        </div>
		    </div>
		    <div class="col-6">
		        <div class="form-group">
		            <strong>Precio:</strong>
                    {!! Form::number('price', null, array('placeholder' => 'Precio','class' => 'form-control')) !!}
		        </div>
		    </div>
		    <div class="col-6">
		        <div class="form-group">
		            <strong>Tags:</strong>
		            {!! Form::select('tags[]', $tags, null, ['class' => 'form-control', 'multiple' => 'multiple']) !!}
		        </div>
		    </div>
		    @if (Auth::user()->hasRole('Admin') || Auth::user()->hasRole('Moderador'))
		    <div class="col-6">
                <div class="form-group">
                    <strong>Foto:</strong>
                    {!! Form::file('image', null) !!}                    
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    <strong>Autor:</strong>
                    {!! Form::select('owner', $users, null, ['class' => 'form-control', 'required' => 'required']) !!}                  
                </div>
            </div>
		    @else
            <div class="col-12">
                <div class="form-group">
                    <strong>Foto:</strong>
                    {!! Form::file('image', null) !!}                    
                </div>
            </div>
            @endif
		    <div class="col-12 text-center">
		            <button type="submit" class="btn btn-primary">Guardar</button>
		    </div>
		</div>
    </form>
@endsection
@section('scripts')
<script>
    $(document).ready( function () {
        $('select').select2({
            maximumSelectionLength: 10,
            tags: true
        });
    });
</script>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-12">
            <div class="float-left">
                <h2>Editar Producto</h2>
            </div>
            <div class="float-right">
                <a class="btn btn-primary" href="{{ route('products.index') }}"> Atras</a>
            </div>
        </div>
    </div>
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Ups!</strong> Hubo algunos problemas con tus datos ingresados.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{ route('products.update',$product->id) }}" method="POST" enctype="multipart/form-data">
    	@csrf
        @method('PUT')
         <div class="row">
		    <div class="col-12">
		        <div class="form-group">
		            <strong>Nombre:</strong>
		            <input type="text" name="name" value="{{ $product->name }}" class="form-control" placeholder="Nombre">
		        </div>
		    </div>
		    <div class="col-12">
		        <div class="form-group">
		            <strong>Detalles:</strong>
		            <textarea class="form-control" style="height:150px" name="detail" placeholder="Detalles">{{ $product->detail }}</textarea>
		        </div>
		    </div>
		    <div class="col-6">
		        <div class="form-group">
		            <strong>Precio:</strong>
		            <input type="number" name="price" value="{{ $product->price }}" class="form-control" placeholder="Precio">
		        </div>
		    </div>
		    <div class="col-6">
		        <div class="form-group">
		            <strong>Tags:</strong>
		            <select name="tags[]" class="form-control form-control-select" multiple="multiple">
		                @foreach ($product->tags as $tag)
		                <option value="{{ $tag }}" selected>{{ $tag }}</option>
		                @endforeach
		            </select>
		        </div>
		    </div>  
            @if (Auth::user()->hasRole('Admin') || Auth::user()->hasRole('Moderador'))
		    <div class="col-6">
                <div class="form-group">
                    <strong>Foto:</strong>
                    {!! Form::file('image', null) !!}                    
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    <strong>Autor:</strong>
                    {!! Form::select('owner', $users, $product->owner, ['class' => 'form-control', 'required' => 'required']) !!}                  
                </div>
            </div>
		    @else
            <div class="col-12">
                <div class="form-group">
                    <strong>Foto:</strong>
                    {!! Form::file('image', null) !!}                    
                </div>
            </div>
            @endif
		    <div class="col-12 text-center">
		      <button type="submit" class="btn btn-primary">Guardar</button>
		    </div>
		</div>
    </form>
@endsection
@section('scripts')
<script>
    $(document).ready( function () {
        $('select').select2({
            maximumSelectionLength: 10,
            tags: true
        });
    });
</script>
@endsection

resources/views/products/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-12">
            <div class="float-left">
                <h2>Productos</h2>
            </div>
            <div class="float-right">
                @can('product-create')
                <a class="btn btn-success" href="{{ route('products.create') }}">Crear Producto</a>
                @endcan
            </div>
        </div>
    </div>
    @if (Session::get('message'))
        <div class="alert alert-{{Session::get('alert')}}">
            {{ Session::get('message') }}
        </div>
    @endif
    <table class="table table-sm table-bordered">
        <thead>
            <tr>
                <th>ID</th>            
                <th>Foto</th>
                <th>Nombre</th>
                <th>Detalles</th>
                <th>Tags</th>
                <th>Precio</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($products as $product)
    	    <tr>
    	        <td>{{ $product->id }}</td>
                <td><img src="{{ url('/public/image', $product->image) }}" class="img-thumbnail width-150"></td>
    	        <td>{{ $product->name }}</td>
    	        <td>{{ $product->detail }}</td>
    	        <td>@foreach ($product->tags as $tag) <label class="badge badge-primary">{{ $tag }}</label> @endforeach</td>
                <td>{{ $product->price }}</td>
    	        <td>            
                    <a class="btn btn-sm btn-info" href="{{ route('products.show',$product->id) }}"><i class="bi bi-eye"></i></a>
                    @can('product-edit')
                    <a class="btn btn-sm btn-primary" href="{{ route('products.edit',$product->id) }}"><i class="bi bi-pencil-square"></i></a>
                    @endcan                
                    @can('product-delete')
                        {!! Form::open(['method' => 'DELETE','route' => ['products.destroy', $product->id],'style'=>'display:inline']) !!}
                            {!! Form::button('<i class="bi bi-trash"></i>', ['class' => 'btn btn-sm btn-danger', 'type' => 'submit']) !!}
                        {!! Form::close() !!}
                    @endcan            
    	        </td>
    	    </tr>
    	    @endforeach
        </tbody>
    </table>
@endsection
@section('scripts')
<script>
    $(document).ready(function() {
        $('.table').DataTable({
            responsive: true,
            /*
            language: {
                url: "{{ url('json/datatables/es-ES.json') }}",
            },
            */
        });
    });
</script>
@endsection

resources/views/products/show.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
    <div class="col-12">
        <div class="float-left">
            <h2>Ver Producto</h2>
        </div>
        <div class="float-right">
            <a class="btn btn-primary" href="{{ route('products.index') }}"> Atras</a>
        </div>
    </div>
</div>
<div class="row text-center">    
    <div class="col-12">
        <div class="form-group">
            <img src="{{ url('/public/image', $product->image) }}" class="img-thumbnail width-500">
        </div>
    </div>
    <div class="col-12">
        <div class="form-group">
            <strong>{{ $product->name }}</strong>
        </div>
    </div>
    <div class="col-12">
        <div class="form-group">
            <strong>$ {{ $product->price }}</strong>
        </div>
    </div>        
    <div class="col-12">
        <div class="form-group">
            {{ $product->detail }}
        </div>
    </div>
</div>
@endsection