routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\FrontEndController;
use App\Http\Controllers\OrdersController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () { return view('welcome'); });
Route::get('/', [FrontEndController::class, 'frontend']);

Auth::routes();
  
Route::get('/dashboard', [HomeController::class, 'index'])->name('dashboard');

Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('products', ProductController::class);
    Route::resource('orders', OrdersController::class);

    Route::post('/orders/store', [OrdersController::class, 'store']);
    //Route::post('/orders/update', [OrdersController::class, 'update']);
    Route::get('/products/get/{product_id}', [ProductController::class, 'get']);
});

app/Models/Orders.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Orders extends Model
{
    use HasFactory;
    
    protected $fillable = [
        'from',
        'to',
        'content',
        'status'
    ];
}

app/Http/Controllers/OrdersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Orders;
use App\Models\Product;
use App\Models\User;

use Auth;
use DB;
use Carbon\Carbon;

class OrdersController extends Controller
{
    function __construct()
    {
         $this->middleware('permission:order-list|order-create|order-edit|order-delete', ['only' => ['index','show']]);
         $this->middleware('permission:order-create', ['only' => ['create','store']]);
         $this->middleware('permission:order-edit', ['only' => ['edit','update']]);
         $this->middleware('permission:order-delete', ['only' => ['destroy']]);
    }
    
    public function index()
    {
        if (Auth::user()->hasRole('Admin') || Auth::user()->hasRole('Moderador')) {
            $orders = Orders::all();
        } else {
            $orders = Orders::where('from', Auth::user()->id)->orWhere('to', Auth::user()->id)->get();
        }
        
        foreach ($orders as $order) {
            $order->content = unserialize($order->content);
            $order->from = $this->get_user_data($order->from, 'name');
            $order->to = $this->get_user_data($order->to, 'name');
        
        }
        
        return view('orders.index',compact('orders'));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        $product = Product::where('id', $request->product)->first();
        $buyer = User::where('id', $request->from)->first();
        $seller = User::where('id', $request->to)->first();
        $order = array();
        
        $order['from'] = $request->from;
        $order['to'] = $request->to;
        
        $content = [
            'product_id' => $request->product,
            'product_name' => $product->name,
            'quantity' => $request->quantity,
            'message' => $request->message,
            'amount' => $request->quantity * $product->price
        ];
        
        $order['content'] = serialize($content);
        $order['status'] = 'pendiente';
        $order['created_at'] = Carbon::now();
        
        $create_order = Orders::insertGetId($order);
        $get_new_order = Orders::where('id', $create_order)->first();
        
        $get_new_order->content = unserialize($get_new_order->content);
        $get_new_order->from = $this->get_user_data($get_new_order->from, 'name') . '(' . $this->get_user_data($get_new_order->from, 'email') . ')';
        $get_new_order->to = $this->get_user_data($get_new_order->to, 'name') . '(' . $this->get_user_data($get_new_order->to, 'email') . ')';
        
        return json_encode($get_new_order->toArray());
    }

    public function show(Orders $orders, $id)
    {
        $order = Orders::where('id', $id)->first();
        
        if (Auth::user()->hasRole('Admin') || Auth::user()->hasRole('Moderador') || $order->from == Auth::user()->id || $order->to == Auth::user()->id) {
            $order->content = unserialize($order->content);
            $order->from = $this->get_user_data($order->from, 'name');
            $order->to = $this->get_user_data($order->to, 'name');
            
            return view('orders.show',compact('order'));
        } else {
            return redirect()->back()->with('alert', 'danger')->with('message','No tiene permisos para ver este pedido.');
        }
    }

    public function edit(Orders $orders)
    {
        //
    }

    public function update(Orders $orders, $id)
    {
        $order = Orders::where('id', $id)->first();
        
        if (Auth::user()->hasRole('Admin') || Auth::user()->hasRole('Moderador') || $order->from == Auth::user()->id || $order->to == Auth::user()->id) {
            
            $switch = ($order->status == 'pendiente') ? 'entregado' : 'pendiente';
            
            $update = Orders::where('id', $order->id)->update(['status' => $switch]);
            
            return redirect()->back()->with('alert', 'success')->with('message','Pedido actualizado.');
        } else {
            return redirect()->back()->with('alert', 'danger')->with('message','No tiene permisos para actualizar este pedido.');
        }
    }

    public function destroy(Orders $orders, $id)
    {
        $order = Orders::where('id', $id)->first();
        
        if (Auth::user()->hasRole('Admin') || Auth::user()->hasRole('Moderador') || $order->from == Auth::user()->id || $order->to == Auth::user()->id) {
            $order->delete();
            
            return redirect()->back()->with('alert', 'success')->with('message','Pedido eliminado.');
        } else {
            return redirect()->back()->with('alert', 'danger')->with('message','No tiene permisos para eliminar este pedido.');
        }
    }
    
    /* HELPERS */
    public function get_user_data($user_id, $field = NULL)
    {
        $user = User::where('id', $user_id)->first();
        
        if (!is_null($user)) {
            if ($field) {
                return $user->$field;
            } else {
                return $user;
            }
        } else {
            return 'Desconocido';
        }
    }
}

resources/views/orders/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-12">
            <div class="float-left">
                <h2>Pedidos</h2>
            </div>
            <div class="float-right">
                @can('order-create')
                <a class="btn btn-success" href="{{ route('orders.create') }}">Crear Pedido</a>
                @endcan
            </div>
        </div>
    </div>
    @if (Session::get('message'))
        <div class="alert alert-{{Session::get('alert')}}">
            {{ Session::get('message') }}
        </div>
    @endif
    <table class="table table-sm table-bordered">
        <thead>
            <tr>
                <th>ID</th>            
                <th>Comprador</th>
                <th>Vendedor</th>
                <th>Monto</th>
                <th>Estado</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($orders as $order)
    	    <tr>
    	        <td>{{ $order->id }}</td>
    	        <td>{{ $order->from }}</td>
    	        <td>{{ $order->to }}</td>
                <td>$ {{ $order->content['amount'] }}</td>
                <td>{{ $order->status }}</td>
    	        <td>
    	            @php
    	            $class = ($order->status == 'pendiente') ? 'btn btn-sm btn-warning' : 'btn btn-sm btn-success';
    	            $icon = ($order->status == 'pendiente') ? '<i class="bi bi-truck"></i>' : '<i class="bi bi-box2-heart-fill"></i>';
    	            @endphp
    	            @if (Auth::user()->hasRole('Admin') || Auth::user()->hasRole('Moderador') || Auth::user()->name == $order->from || Auth::user()->name == $order->to)
    	                {!! Form::open(['method' => 'PUT','route' => ['orders.update',$order->id],'style'=>'display:inline']) !!}
                            {!! Form::button($icon, ['class' => $class, 'type' => 'submit']) !!}
                        {!! Form::close() !!}
    	            @endif
                    <a class="btn btn-sm btn-info" href="{{ route('orders.show',$order->id) }}"><i class="bi bi-eye"></i></a>
                    @can('product-edit')
                    <a class="btn btn-sm btn-primary" href="{{ route('orders.edit',$order->id) }}"><i class="bi bi-pencil-square"></i></a>
                    @endcan                
                    @can('product-delete')
                        {!! Form::open(['method' => 'DELETE','route' => ['orders.destroy', $order->id],'style'=>'display:inline']) !!}
                            {!! Form::button('<i class="bi bi-trash"></i>', ['class' => 'btn btn-sm btn-danger', 'type' => 'submit']) !!}
                        {!! Form::close() !!}
                    @endcan            
    	        </td>
    	    </tr>
    	    @endforeach
        </tbody>
    </table>
@endsection
@section('scripts')
<script>
    $(document).ready(function() {
        $('.table').DataTable({
            responsive: true,
            /*
            language: {
                url: "{{ url('json/datatables/es-ES.json') }}",
            },
            */
        });
    });
</script>
@endsection

resources/views/orders/show.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
    <div class="col-12">
        <div class="float-left">
            <h2>Ver Pedido</h2>
        </div>
        <div class="float-right">
            <a class="btn btn-primary" href="{{ route('orders.index') }}"> Atras</a>
        </div>
    </div>
</div>
<div class="row">    
    <div class="col-2">
    </div>
    <div class="col-8">
        <div class="row">
            <div class="col-12 mb-10 border border-secondary">
                <p class="float-right">Fecha: {{ $order->created_at }}</p>
            </div>
            <div class="col-6 border border-secondary">
                <div class="float-left">
                    <p><strong>Datos del Comprador</strong></p>
                    <p>Nombre: {{ $order->from }}</p>
                </div>
            </div>
            <div class="col-6 border border-secondary">
                <div class="float-left">
                    <p><strong>Datos del Vendedor</strong></p>
                    <p>Nombre: {{ $order->to }}</p>
                </div>
            </div>
            <div class="col-12 border border-secondary p-0 m-0">
                <table class="table table-striped table-bordered p-0 m-0">
                    <thead>
                        <tr>
                            <th>Producto</th>
                            <th>Cantidad</th>
                            <th>Precio</th>
                            <th>Subtotal</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{ $order->content['product_name'] }}</td>
                            <td>{{ $order->content['quantity'] }}</td>
                            <td>$ {{ $order->content['amount'] / $order->content['quantity'] }}</td>
                            <td>$ {{ $order->content['amount'] }}</td>
                        </tr>
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="3"></td>
                            <td><strong>Total:</strong> $ {{ $order->content['amount'] }}</td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
    <div class="col-2">
    </div>
</div>
@endsection